FROM	tensin-base-debian

RUN	apt-get update && apt-get install -y curl python3 python3-pip && apt-clean # && \
	# curl -sL https://bootstrap.pypa.io/get-pip.py | python3 && \
	# ln -s /usr/bin/python3 /usr/bin/python
