FROM	tensin-base-debian

RUN	apt-get update && apt-get install -y curl ca-certificates tar && apt-clean

# Set environment
ENV	JAVA_HOME /opt/jdk
ENV	PATH ${PATH}:${JAVA_HOME}/bin
ENV	JAVA_PACKAGE       jdk

# Download and unarchive Java
ADD 	jdk-7u80-linux-i586.tar.gz	/opt/

# Download and unarchive Java
RUN	ln -s $(ls -d1 /opt/${JAVA_PACKAGE}* | tail -1) /opt/jdk && \
    rm -rf /opt/jdk/*src.zip \
           /opt/jdk/lib/missioncontrol \
           /opt/jdk/lib/visualvm \
           /opt/jdk/lib/*javafx* \
           /opt/jdk/jre/lib/plugin.jar \
           /opt/jdk/jre/lib/ext/jfxrt.jar \
           /opt/jdk/jre/bin/javaws \
           /opt/jdk/jre/lib/javaws.jar \
           /opt/jdk/jre/lib/desktop \
           /opt/jdk/jre/plugin \
           /opt/jdk/jre/lib/deploy* \
           /opt/jdk/jre/lib/*javafx* \
           /opt/jdk/jre/lib/*jfx* \
           /opt/jdk/jre/lib/amd64/libdecora_sse.so \
           /opt/jdk/jre/lib/amd64/libprism_*.so \
           /opt/jdk/jre/lib/amd64/libfxplugins.so \
           /opt/jdk/jre/lib/amd64/libglass.so \
           /opt/jdk/jre/lib/amd64/libgstreamer-lite.so \
           /opt/jdk/jre/lib/amd64/libjavafx*.so \
           /opt/jdk/jre/lib/amd64/libjfx*.so
